# Generated by Django 5.1.7 on 2025-03-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phamaciens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('sexe', models.CharField(default='', max_length=15)),
                ('nomphamacie', models.CharField(default='', max_length=100)),
                ('descrp', models.CharField(default='Pas de description', max_length=300)),
                ('datenaissance', models.CharField(default='00/00/0000', max_length=15)),
                ('tel', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=150)),
                ('nomPhamaciens', models.CharField(default='', max_length=100)),
                ('motdepasse', models.CharField(default='', max_length=100)),
                ('Cmotdepasse', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='phamacien', max_length=30)),
                ('code', models.CharField(default='', max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('poids', models.CharField(default='', max_length=30)),
                ('etat', models.CharField(default='', max_length=50)),
                ('couleur', models.CharField(default='', max_length=50)),
                ('prix', models.CharField(default='', max_length=50)),
                ('nbr_comprime', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(null=True, upload_to='images/produits/')),
                ('date_enreg', models.CharField(max_length=100)),
                ('phamaciens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='PhamacieApp.phamaciens')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('tel', models.CharField(default='', max_length=50)),
                ('quantité', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=200)),
                ('date_demd', models.DateTimeField()),
                ('decisions', models.CharField(default='0', max_length=100)),
                ('phamaciens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande', to='PhamacieApp.phamaciens')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande', to='PhamacieApp.produit')),
            ],
        ),
    ]
