# Generated by Django 5.1.7 on 2025-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamacieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='payer',
            field=models.BooleanField(default=0),
        ),
    ]
