# Generated by Django 5.1.7 on 2025-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamacieApp', '0002_demande_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phamaciens',
            name='descrp',
            field=models.CharField(default='Pas de description', max_length=1000),
        ),
    ]
