# Generated by Django 5.1.7 on 2025-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamacieApp', '0003_alter_phamaciens_descrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='img_qr',
            field=models.ImageField(null=True, upload_to='images/qr/'),
        ),
    ]
